# workflows to sync files before continuing with other push/pull CIs
name: Sync

on:
  push:
    paths:
      - 'README.md'
  pull-request:
    paths:
      - 'config/crd/bases/**.yaml'

env:
  GITHUB_USER_NAME: github-actions
  GITHUB_USER_EMAIL: github-actions@github.com

jobs:
  sync-readme:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Push README to gh-pages branch
        run: |
          git config user.name "$GITHUB_USER_NAME"
          git config user.email "$GITHUB_USER_EMAIL"
          git fetch -a
          git checkout $GITHUB_SHA -- README.md
          mv README.md index.md
          git add index.md README.md
          if git commit -m "Sync readme from commit $GITHUB_SHA"; then
            git push origin gh-pages
          else
            echo "Nothing committed, not pushing."
          fi

  sync-crds:
    if: ${{ github.event_name == 'pull-request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy CRDs to helm chart
        run: |
          cp config/crd/bases/*.yaml charts/aws-pca-issuer/crds/
      - name: Update pull request
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ github.base_ref }}
          path: "charts/"
          commit-message: "Sync CRDs from config to charts from commit ${{ github.sha }}"
          author: "${{ env.GITHUB_USER_NAME }} <${{ env.GITHUB_USER_EMAIL }}>"

  # sync-crds:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Copy CRDs to helm chart
  #       run: |
  #         git config user.name "$GITHUB_USER_NAME"
  #         git config user.email "$GITHUB_USER_EMAIL"
  #         cp config/crd/bases/*.yaml charts/aws-pca-issuer/crds/
  #         git add charts
  #         if git commit -m "Sync CRDs from config to charts from commit $GITHUB_SHA"; then
  #           git push origin main
  #         else
  #           echo "Nothing committed, not pushing"
  #         fi