# workflows to sync files before continuing with other push/pull CIs
name: Sync

on:
  push:
    paths:
      - 'README.md'
      - 'config/crd/bases/**.yaml'

env:
  GITHUB_USER_NAME: GitHub Actions
  GITHUB_USER_EMAIL: githubactions@users.noreply.github.com

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Push README to gh-pages branch
        run: |
          git config --global user.name "$GITHUB_USER_NAME"
          git config --global user.email "$GITHUB_USER_EMAIL"
          git fetch -a
          git checkout $GITHUB_SHA -- README.md
          mv README.md index.md
          git add index.md README.md
          if git commit -m "Sync readme from commit $GITHUB_SHA"; then
            git push origin gh-pages
          else
            echo "Nothing committed, not pushing."
          fi

  sync-crds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy CRDs to helm chart and push
        run: |
          git config --global user.name "$GITHUB_USER_NAME"
          git config --global user.email "$GITHUB_USER_EMAIL"
          git fetch -a
          cp config/crd/bases/*.yaml charts/aws-pca-issuer/crds/
          git add charts
          if git commit -m "Sync CRDs from config to charts from commit $GITHUB_SHA"; then
            git push origin main
          else
            echo "Nothing committed, not pushing"
          fi